from pygame import *


class MouseButtons:
    LEFT = 'LEFT'
    MIDDLE = 'MIDDLE'
    RIGHT = 'RIGHT'


class Command:
    UP_START = 'UP_START'
    UP_END = 'UP_END'
    DOWN_START = 'DOWN_START'
    DOWN_END = 'DOWN_END'
    LEFT_START = 'LEFT_START'
    LEFT_END = 'LEFT_END'
    RIGHT_START = 'RIGHT_START'
    RIGHT_END = 'RIGHT_END'
    SPACE_START = 'SPACE_START'
    SPACE_END = 'SPACE_END'
    RIGHT_MOUSE_START = 'RIGHT_MOUSE_START'
    LEFT_MOUSE_START = 'LEFT_MOUSE_START'
    ESCAPE = 'ESCAPE'
    ENTER = 'ENTER'
    TAB = 'TAB'
    Q = 'Q'
    W = 'W'
    C = 'C'
    QUIT = 'QUIT'
    MOUSE_LEFT_UP = 'MOUSE_LEFT_UP'
    MOUSE_LEFT_DOWN = 'MOUSE_LEFT_DOWN'
    MOUSE_MIDDLE_UP = 'MOUSE_MIDDLE_UP'
    MOUSE_MIDDLE_DOWN = 'MOUSE_MIDDLE_DOWN'
    MOUSE_RIGHT_UP = 'MOUSE_RIGHT_UP'
    MOUSE_RIGHT_DOWN = 'MOUSE_RIGHT_DOWN'
    MOUSEMOTION = 'MOUSEMOTION'
    X_KEY = 'X_KEY'

    K_RIGHT_MOUSE = 3


commands = {
    (KEYDOWN, K_UP): Command.UP_START,
    (KEYUP, K_UP): Command.UP_END,
    (KEYDOWN, K_DOWN): Command.DOWN_START,
    (KEYUP, K_DOWN): Command.DOWN_END,
    (KEYDOWN, K_LEFT): Command.LEFT_START,
    (KEYUP, K_LEFT): Command.LEFT_END,
    (KEYDOWN, K_RIGHT): Command.RIGHT_START,
    (KEYUP, K_RIGHT): Command.RIGHT_END,
    (KEYDOWN, K_SPACE): Command.SPACE_START,
    (KEYUP, K_SPACE): Command.SPACE_END,
    (MOUSEBUTTONDOWN, Command.K_RIGHT_MOUSE): Command.RIGHT_MOUSE_START,
    (KEYDOWN, K_ESCAPE): Command.ESCAPE,
    (KEYDOWN, K_TAB): Command.TAB,
    (MOUSEBUTTONDOWN, MouseButtons.LEFT): Command.MOUSE_LEFT_DOWN,
    (MOUSEBUTTONUP, MouseButtons.LEFT): Command.MOUSE_LEFT_UP,
    (MOUSEBUTTONDOWN, MouseButtons.MIDDLE): Command.MOUSE_MIDDLE_DOWN,
    (MOUSEBUTTONUP, MouseButtons.MIDDLE): Command.MOUSE_MIDDLE_UP,
    (MOUSEBUTTONDOWN, MouseButtons.RIGHT): Command.MOUSE_RIGHT_DOWN,
    (MOUSEBUTTONUP, MouseButtons.RIGHT): Command.MOUSE_RIGHT_UP,
    MOUSEMOTION: Command.MOUSEMOTION,
    K_x: Command.X_KEY,
    (KEYDOWN, K_c): Command.C,
    (KEYDOWN, K_q): Command.Q,
    (KEYDOWN, K_w): Command.W,
    (KEYDOWN, K_RETURN): Command.ENTER,
    QUIT: Command.QUIT
}
